name: Build Windows TV
on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./simple_live_tv_app

      - name: Build Windows
        run: flutter build windows --release
        working-directory: ./simple_live_tv_app

      # 调试：打印目录，确认编译产物真实存在
      - name: List build output
        run: Get‑ChildItem simple_live_tv_app/build/windows -Recurse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-tv-windows
          path: simple_live_tv_app/build/windows/**
          if-no-files-found: error
