name: build apk
on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - run: flutter pub get
        working‑directory: ./simple_live_app

      - run: flutter build apk --release
        working‑directory: ./simple_live_app

      - name: upload artifact
        uses: actions/upload‑artifact@v4
        with:
          name: app‑apk
          path: simple_live_app/build/app/outputs/flutter‑apk/release/app‑release.apk
